Team-5/Models/Animals.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Team_5.Models
{
    public class Animals
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdAnimal { get; set; }

        [Required]
        [StringLength(50)]
        public required string Name { get; set; }

        [Required]
        public required DateTime RegistrationDate { get; set; }

        [Required]
        public required DateTime BirthDate { get; set; }

        [StringLength(16)]
        public string? NumMicrochip { get; set; }

        public byte[]? Image { get; set; }

        [Required]
        [StringLength(20)]
        public required string Color { get; set; }

        //RIFERIMENTI EF
        public int? OwnerId { get; set; }

        [ForeignKey(nameof(OwnerId))]
        public Owners? Owner { get; set; }

        public List<Hospitalizations>? Hospitalization { get; set; } = [];

        public List<Examinations>? Examination { get; set; } = [];

        [Required]
        public required Breeds Breed { get; set; }


    }
}

Team-5/Models/Clinic/Animals.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace Team_5.Models.Clinic
{
    public class Animals
    {
        [Required(ErrorMessage = "Seleziona un animale.")]
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdAnimal { get; set; }

        [Required(ErrorMessage = "Il nome dell'animale è obbligatorio.")]
        [StringLength(50)]
        public required string Name { get; set; }

        [Required(ErrorMessage = "La data di registrazione è obbligatoria.")]
        public required DateTime RegistrationDate { get; set; }

        [Required(ErrorMessage = "La data di nascita è obbligatoria.")]
        public DateTime BirthDate { get; set; } = DateTime.MinValue;

        [StringLength(16)]
        [Required(ErrorMessage = "Il numero di microchip è obbligatorio.")]
        public string NumMicrochip { get; set; }

        public byte[]? Image { get; set; }

        [Required(ErrorMessage = "Il colore dell'animale è obbligatorio.")]
        [StringLength(20)]
        public required string Color { get; set; }

        //RIFERIMENTI EF
        public int? OwnerId { get; set; }

        [ForeignKey(nameof(OwnerId))]
        public Owners? Owner { get; set; }

        public List<Hospitalizations>? Hospitalization { get; set; } = new();

        [JsonIgnore]
        public List<Examinations>? Examination { get; set; } = new();

        [Required(ErrorMessage = "La razza è obbligatoria.")]
        public Breeds Breed { get; set; }
    }
}

Team-5/Models/ViewModels/CreateAnimalViewModel.cs
using System.ComponentModel.DataAnnotations;
using Team_5.Models.Clinic;

namespace Team_5.Models.ViewModels
{
    public class CreateAnimalViewModel
    {
        [Required(ErrorMessage = "Il nome dell'animale è obbligatorio.")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Il nome può contenere solo lettere e spazi.")]
        [StringLength(50)]
        public required string Name { get; set; }

        [Required(ErrorMessage = "La data di registrazione è obbligatoria.")]
        public required DateTime RegistrationDate { get; set; }

        [Required(ErrorMessage = "La data di nascita è obbligatoria.")]
        public DateTime BirthDate { get; set; } = DateTime.MinValue;

        [StringLength(16)]
        [Required(ErrorMessage = "Il numero di microchip è obbligatorio.")]

        public string NumMicrochip { get; set; }

        public IFormFile? Image { get; set; }

        [Required(ErrorMessage = "Il colore dell'animale è obbligatorio.")]
        [StringLength(20)]
        public required string Color { get; set; }

        public int? OwnerId { get; set; }

        [Required(ErrorMessage = "La razza dell'animale è obbligatoria.")]
        public int SelectedBreedId { get; set; }


        public int? SelectedOwnerId { get; set; }

        public List<Breeds>? Breeds { get; set; } = [];
        public List<Owners>? Owners { get; set; } = [];
    }
}

Team-5/Controllers/AnimalsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Team_5.Models.ViewModels;
using Team_5.Services.Interfaces;

namespace Team_5.Controllers
{
    [Authorize(Policy = "VetPolicy")]
    public class AnimalsController : Controller
    {
        private readonly IAnimalsService _animalsSvc;
        private readonly IBreedsService _breedSvc;

        public AnimalsController(IAnimalsService animalsService, IBreedsService breedsService)
        {
            _animalsSvc = animalsService;
            _breedSvc = breedsService;
        }

        [HttpGet]

        public async Task<IActionResult> CreateAnimal()
        {
            var viewModel = await _animalsSvc.GetCreateAnimalViewModelAsync();
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> CreateAnimal(CreateAnimalViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var animal = await _animalsSvc.CreateAnimalAsync(viewModel);
                    return RedirectToAction("AnimalList");
                }
                catch (ArgumentException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            viewModel.Breeds = await _breedSvc.GetAllBreedsAsync();
            return View(viewModel);
        }

        public async Task<IActionResult> AnimalList()
        {
            var animals = await _animalsSvc.GetAllAnimalsAsync();
            return View(animals);
        }

        public IActionResult GetAnimalByMicrochip()
        {
            return View();
        }


        [HttpGet("Animals/GetAnimalDataByMicrochip")]
        public async Task<IActionResult> GetAnimalDataByMicrochip(string microchipId)
        {
            var animals = await _animalsSvc.GetAnimalByMicrochipAsync(microchipId);
            var animalData = animals.Select(animal => new
            {
                animal.Name,
                RegistrationDate = animal.RegistrationDate.ToString("yyyy-MM-dd"),
                BirthDate = animal.BirthDate.ToString("yyyy-MM-dd"),
                animal.Color,
                Image = animal.Image != null ? Convert.ToBase64String(animal.Image) : null,
                IsHospitalized = animal.Hospitalization != null && animal.Hospitalization.Any(h => h.IsHospitalized)
            }).ToList();

            return Ok(animalData);
        }


        public async Task<IActionResult> AnimalsWithoutOwner()
        {
            var animals = await _animalsSvc.GetAnimalsWithoutOwnerAsync();
            return View(animals);
        }

        // eliminazione animale

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAnimal(int id)
        {
            var success = await _animalsSvc.DeleteAnimalAsync(id);
            if (!success)
            {
                return NotFound();
            }

            return RedirectToAction("AnimalList");
        }
    }
}

Team-5/Controllers/ExaminationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Team_5.Models.Clinic;
using Team_5.Services.Interfaces;

namespace Team_5.Controllers
{
    [Authorize(Policy = "VetPolicy")]
    public class ExaminationController : Controller
    {
        private readonly IExaminationService _examinationSvc;

        public ExaminationController(IExaminationService examinationService)
        {
            _examinationSvc = examinationService;
        }

        [HttpGet]
        public async Task<IActionResult> CreateExaminationAsync()
        {
            var animals = await _examinationSvc.GetAllAnimalsAsync();
            ViewBag.Animals = animals;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateExaminationAsync(Examinations ex)
        {
            var animalExists = await _examinationSvc.AnimalExistsAsync(ex.AnimalId);
            if (!animalExists)
            {
                ModelState.AddModelError("AnimalId", "Invalid Animal ID");
                return View(ex);
            }

            await _examinationSvc.CreateExaminationAsync(ex);
            return RedirectToAction("ExaminationsList");
        }

        [HttpGet]
        public async Task<IActionResult> ExaminationsList()
        {
            var esami = await _examinationSvc.GetAllExaminationsAsync();
            return View(esami);
        }

        [HttpGet("Examination/ExaminationsListByIdAnimal")]
        public async Task<IActionResult> ExaminationsListByIdAnimal([FromQuery] int IdAnimal)
        {
            var esamiByAnimalId = await _examinationSvc.GetAllExaminationsByIdAnimalAsync(IdAnimal);
            return Ok(esamiByAnimalId);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteExamination(int id)
        {
            var deletedExam = await _examinationSvc.DeleteExamination(id);

            if (deletedExam == null)
            {
                // Se l'ordine non esiste, restituisci un 404 Not Found
                return NotFound(new { Message = "Order not found." });
            }

            return RedirectToAction("ExaminationsList");

        }
    }
}

Team-5/Views/Animals/AnimalList.cshtml
@model List<Team_5.Models.Clinic.Animals>

@{
    ViewData["Title"] = "Lista Animali";
}
<div class="row">
    <div class="col">
<h1 class="text-light">Lista Animali</h1>
<hr />

<table class="table table-dark-personal">
    <thead class="personal-tr">
        <tr class="personal-tr p-2">
            <th scope="col">Nome</th>
            <th scope="col">Data di Registrazione</th>
            <th scope="col">Data di Nascita</th>
            <th scope="col">Razza</th>
            <th scope="col">Colore</th>
            <th scope="col">N.Microchip</th>
            <th scope="col">ID Padrone</th>
            <th scope="col">Immagine</th>
            <th scope="col">Azioni</th> 
        </tr>
    </thead>
    <tbody class="p-2">
        @foreach (var animal in Model)
        {
            <tr>
                <td>@animal.Name</td>
                <td>@animal.RegistrationDate.ToString("yyyy-MM-dd")</td>
                <td>@animal.BirthDate.ToString("yyyy-MM-dd")</td>
                <td>@animal.Breed?.Name</td>
                <td>@animal.Color</td>
                <td>@animal.NumMicrochip</td>
                <td>@animal.OwnerId</td>
                <td>
                    @if (animal.Image != null && animal.Image.Length > 0)
                    {
                        <img src="data:image/png;base64,@Convert.ToBase64String(animal.Image)" alt="Animal Image" style="width: 100px; height: auto;" />
                    }
                    else
                    {
                        <span>Nessuna immagine</span>
                    }
                </td>
                <td>
                    <form asp-action="DeleteAnimal" method="post" onsubmit="return confirm('Sei sicuro di voler eliminare questo animale?');">
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="id" value="@animal.IdAnimal" />
                        <button type="submit" class="btn btn-grey">Elimina</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>
    </div>
</div>

Team-5/Views/Animals/AnimalsWithoutOwner.cshtml
@model List<Team_5.Models.Clinic.Animals>

@{
    ViewData["Title"] = "Animali senza Proprietario";
}
<div class="row">
    <div class="col">
        <h1 class="text-light">Animali senza Proprietario</h1>
        <hr />

        <table class="table table-dark-personal">
            <thead class="personal-tr">
                <tr class="personal-tr">
                    <th scope="col">Nome</th>
                    <th scope="col">Data di Registrazione</th>
                    <th scope="col">Data di Nascita</th>
                    <th scope="col">Colore</th>
                    <th scope="col">Razza</th>
                    <th scope="col">Immagine</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var animal in Model)
                {
                    <tr>
                        <td>@animal.Name</td>
                        <td>@animal.RegistrationDate.ToShortDateString()</td>
                        <td>@animal.BirthDate.ToShortDateString()</td>
                        <td>@animal.Color</td>
                        <td>@animal.Breed.Name</td>
                        
                        <td>
                            @if (animal.Image != null && animal.Image.Length > 0)
                            {
                                <img src="data:image/png;base64,@Convert.ToBase64String(animal.Image)" alt="Animal Image" style="width: 100px; height: auto;" />
                            }
                            else
                            {
                                <span>Nessuna immagine</span>
                            }
                        </td>
                        <td>
                            <form asp-action="DeleteAnimal" method="post" onsubmit="return confirm('Sei sicuro di voler eliminare questo animale?');">
                                @Html.AntiForgeryToken()
                                <input type="hidden" name="id" value="@animal.IdAnimal" />
                                <button type="submit" class="btn btn-grey">Elimina</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

Team-5/Views/Animals/CreateAnimal.cshtml
@using Team_5.Models.ViewModels
@model CreateAnimalViewModel

@{
    var ownerItems = Model.Owners.Select(o => new SelectListItem
            {
                Value = o.IdOwner.ToString(),
                Text = $"{o.Name} {o.Surname} - ID: {o.IdOwner}"
            }).ToList();
}
<link rel="stylesheet" href="~/css/auth.css" />

@{
    ViewData["Title"] = "Aggiungi Animale";
}


<div class="row align-items-center justify-content-center">
    <div class="col-12 col-sm-10 col-md-9 col-lg-8 col-xl-7">
        <div class="bg-custom rounded p-5 my-4 mx-3">
            <div class="d-flex align-items-center justify-content-between mb-3">
                <h3 class="text-red">REGISTRAZIONE ANIMALE</h3>
                <h3 class="text-light">Creazione <i class="fa-solid fa-dog text-red"></i></h3>
            </div>
            <form asp-action="CreateAnimal" method="post" enctype="multipart/form-data">
                @Html.AntiForgeryToken()

                <div class="form-group">
                    <label asp-for="Name" class="control-label mb-1 text-light">Inserisci nome animale:</label>
                    <input asp-for="Name" class="form-control bg-secondary text-light" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-group mt-2">
                    <label asp-for="RegistrationDate" class="control-label mb-1 text-light mt-2">Data di registrazione:</label>
                    <input asp-for="RegistrationDate" class="form-control bg-secondary text-light" type="date" disabled />
                    <span asp-validation-for="RegistrationDate" class="text-danger"></span>
                </div>

                <div class="form-group mt-2">
                    <label asp-for="BirthDate" class="control-label mb-1 text-light mt-2">Inserisci data di nascita:</label>
                    <input asp-for="BirthDate" class="form-control bg-secondary text-light" type="date" />
                    <span asp-validation-for="BirthDate" class="text-danger"></span>
                </div>

                <div class="form-group mt-2">
                    <label asp-for="NumMicrochip" class="control-label  mb-1 text-light mt-2">Inserisci num. microchip:</label>
                    <input asp-for="NumMicrochip" class="form-control bg-secondary text-light" />
                    <span asp-validation-for="NumMicrochip" class="text-danger"></span>
                </div>

                <div class="form-group my-3">
                    <div class="d-flex align-items-center">
                        <label asp-for="Image" class="control-label mb-1 text-light mt-2">Inserisci immagine:</label>
                        <div class="custom-file-upload ms-3">
                            <input asp-for="Image" type="file" id="fileInput" />
                            <label for="fileInput" class="btn btn-primary">Scegli file</label>
                        </div>
                    </div>

                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>


                <div class="form-group">
                    <label asp-for="Color" class="control-label mb-1 text-light mt-2">Inserisci colore animale:</label>
                    <select asp-for="Color" class="form-control bg-secondary text-light">
                        <option value="" disabled selected>Seleziona un colore</option>
                        <option value="Black">Nero</option>
                        <option value="White">Bianco</option>
                        <option value="Brown">Marrone</option>
                        <option value="Gray">Grigio</option>
                        <option value="Orange">Arancione</option>
                        <option value="Spotted">Maculato</option>
                        <option value="Striped">Tigrato</option>
                    </select>
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div>

                <div class="form-group mt-2">
                    <label asp-for="SelectedOwnerId" class="control-label mb-1 text-light mt-2">Inserisci proprietario:</label>
                    <select asp-for="SelectedOwnerId" asp-items="ownerItems" class="form-control bg-secondary text-light">
                        <option value="" disabled selected>Seleziona un proprietario</option>
                    </select>
                    <span asp-validation-for="SelectedOwnerId" class="text-danger"></span>
                </div>

                <div class="form-group mt-2">
                    <label asp-for="SelectedBreedId" class="control-label mb-1 text-light mt-2">Inserisci razza animale:</label>
                    <select asp-for="SelectedBreedId" asp-items="@(new SelectList(Model.Breeds, "IdBreed", "Name"))" class="form-control bg-secondary text-light">
                        <option value="" disabled selected>Seleziona una razza</option>
                    </select>
                    <span asp-validation-for="SelectedBreedId" class="text-danger"></span>
                </div>
                <input type="submit" value="Crea" class="btn btn-red py-3 w-100 my-4 text-white" />
                
            </form>
        </div>
<a asp-action="AnimalList" class="btn btn-blu mt-2">Torna Alla Lista</a>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Team-5/Views/Animals/GetAnimalByMicrochip.cshtml
@{
    ViewData["Title"] = "Trova Animale per Microchip";
}

<h1 class="text-personal">@ViewData["Title"]</h1>
<hr />


<link rel="stylesheet" href="~/css/auth.css" />


<div class="row align-items-center justify-content-center">
    <div class="col-12 col-sm-10 col-md-9 col-lg-8 col-xl-7">
        <div class="bg-custom rounded p-5 my-4 mx-3">
            <div class="d-flex align-items-center justify-content-between mb-3">
                <h3 class="text-red">RICERCA PER MICROCHIP</h3>
                <h3 class="text-light">Ricerca <i class="fa-solid fa-magnifying-glass text-red"></i></i></h3>
            </div>
                @Html.AntiForgeryToken()
                <h2 class="control-label mb-1 text-light">Inserisci il numero del microchip:</h2>
                <div class="input-group mt-4 mb-4">
                <input type="text" id="microchip" class="form-control bg-secondary text-light" placeholder="Es. 1234567890" aria-label="Numero Microchip" />
                </div>
            <div id="animals" class="mt-4"></div>
            <a asp-controller="Examination" asp-action="ExaminationsList" class="btn btn-red mt-2">Torna Alla Lista</a>


        </div>
    
    </div>
</div>